skip_local_validator = true

[toolchain]

[features]
resolution = true
skip-lint = false

[programs.localnet]
remittance_stablecoin = "CWmj86ohTg2kz1FnmEmHB8EBRuBxc9UQRHTnu4NV7Ygt"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "cargo test"

[hooks]
